### ISSUE TITLE
[Question] 

### ISSUE THREAD

**Issue by louigi600** [telekom-mms/keepassxc-p11-wrapper#4]
### Question

I was unable to build the wrapper:
[root@optiplex keepassxc-p11-wrapper]# go build ./cmd/keepassxc-p11-wrapper
go: downloading github.com/sirupsen/logrus v1.9.0
go: downloading pault.ag/go/pkcs7 v0.0.0-20220605185533-916a162b6ad9
go: downloading github.com/gopasspw/pinentry v0.0.2
go: downloading github.com/miekg/pkcs11 v1.1.1
go: downloading golang.org/x/sys v0.7.0
internal/keepassxc/keydata.go:13:2: unrecognized import path "pault.ag/go/pkcs7": https fetch: Get "https://pault.ag/go/pkcs7?go-get=1": tls: failed to verify certificate: x509: certificate signed by unknown authority
[root@optiplex keepassxc-p11-wrapper]#

How do I fix that ?

**Comment by jandd** [comment]
Seems like your Go installation does not trust the certificate used by https://pault.ag/. The certificate is signed by Amazon and should be trusted by most operating systems/browsers, etc. This is an issue with your Go installation and/or client operating system and nothing we can fix.

**Comment by louigi600** [comment]
Ok,  but just so you know I'm using Fedora 38, it's not like I'm using one unknown linux distribution that only 10 other people are using in the entire world.
Can I manually download the stuff and avoid go fetching it ? If so where do I put it ?
